upgrade to python3
for this error

```
  File "RsaCtfTool.py", line 15, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey
```

`PyCrypto` is missing but not available in arch or blackarch repos.

requirements.txt: https://github.com/Ganapati/RsaCtfTool/blob/master/requirements.txt

https://github.com/Ganapati/RsaCtfTool/blob/master/RsaCtfTool.py#L1 = `#!/usr/bin/env python3`